### ISSUE TITLE
Graph options sometimes don't set

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#12]
Looks like I have to add or remove any widget to "force" it to update it's settings.

**Comment by Gold872** [comment]
Could you send a video of this happening?

**Comment by daltzctr** [comment]
https://github.com/Gold872/elastic-dashboard/assets/105223895/eed0d5e5-5ad2-483b-a869-460df8c4058b

**Comment by Gold872** [comment]
You have to hit enter before clicking "Close". From what I know this is a limitation of Flutter so I don't think I can fix this.

**Comment by daltzctr** [comment]
Can there be a "confirm" or "save" button?

**Comment by Gold872** [comment]
I'll think about a way of doing this since it's a good idea

**Comment by Gold872** [comment]
I finally figured out the solution to this. It had to do with the graph widget being a stateful widget that wasn't in a stream builder. The solution was very convoluted but the widget should now successfully rebuild when you change its settings.
