### ISSUE TITLE
Shuffleboard-metadata widgets are added to tab even if they already exist

### ISSUE THREAD

**Issue by shueja** [Gold872/elastic-dashboard#18]
Hi, I'm testing Elastic with code-generated layouts, and I'm seeing that every time I restart sim, all the widgets are added again to the tab, so that I have several sets of widgets all piling up in the corner grid square. I'm not using size or position metadata, just PreferredComponent. Is this intentional?

**Comment by Gold872** [comment]
I'm a bit confused, do they keep adding even if they already exist on the tab or is the issue that they're not going to any position? I discovered an issue recently that's similar to this and I've patched it for the next update, but could you send me the code so I can try to reproduce this?

With the positioning, it doesn't automatically find a free space to place the widget, currently it just puts it at 0, 0 which is the top left corner. I've been thinking of ways to fix it but at the moment it doesn't really do anything.
