### ISSUE TITLE
Add the option to switch tabs based on some condition

### ISSUE THREAD

**Issue by katzuv** [Gold872/elastic-dashboard#22]
One way to implement that is to have a constant entry that holds the name of the tab which should be active/in focus.
A few use cases I thought of:
- Before the match starts, switch to "Autonomous Configuration" tab (switch when [`DriverStation.isFMSAttached()`](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/DriverStation.html#isFMSAttached()) is true).
- When teleop starts switch to another tab than the one displayed in auto.
- When running test functions in the pit that check subsystems, switch between subsystem-specific tabs when each subsystem check is finished (another way is to use the same tab and between every subsystem delete widgets and add others, but that may be harder to implement).

**Comment by Gold872** [comment]
This can be done via robot code by using the [select tab method](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.html#selectTab(java.lang.String)) of the Shuffleboard API. Whenever you use that method in your robot code, Elastic will switch to the tab you want to select if the tab exists

Here's the WPILib documentation for this part of the Shuffleboard API: https://docs.wpilib.org/en/stable/docs/software/dashboards/shuffleboard/layouts-with-code/using-tabs.html
