### ISSUE TITLE
Unable to Create tabs via Shuffleboard API

### ISSUE THREAD

**Issue by m10653** [Gold872/elastic-dashboard#28]
**Describe the bug**
Utilizing the shuffleboard api and the getTab method fails to create a new tab. Where as the exact same code will cause a new tab to be created within shuffleboard dashboard itself.

**To Reproduce**
1. Run Shuffleboard.getTab("test");
2. Shuffleboard.selectTab("test");
3. Tab is created and switched to via Shuffleboard Dashboard
4. Elastic fails to do so.

**Expected behavior**

**Screenshots**
Bug shown where tab Autonomous2 is not being created.
![bug](https://github.com/Gold872/elastic-dashboard/assets/13669738/086823cf-f5e2-4f3c-91bc-b639a7b8c883)

**Desktop (please complete the following information):**
 - OS:  Windows
 - WPILIb:  2024.1.1 - Java
 - Elastic  2024.0.2
 
**Additional context**

**Comment by Gold872** [comment]
Elastic only creates a tab via the shuffleboard api when there's a new widget to be placed. I'll try experimenting with being able to create a tab when there's nothing on it, but I'm not sure if I will be able to get it reliably working. The shuffleboard schema on network tables is very finnicky and was a huge pain to get working consistently.

**Comment by Gold872** [comment]
Feature has been added and will be released in the next update
