### ISSUE TITLE
Incorrect field property definition for robot height in documentation.

### ISSUE THREAD

**Issue by rtsledge** [Gold872/elastic-dashboard#30]
On Widget List and Properties Page for the field widget under properties robot "height" is defined as 

robot_height - The length of the robot in meters (defaults to 0.85)
Decimal number 
![Capture](https://github.com/Gold872/elastic-dashboard/assets/156355055/9a7cb85e-f4ae-4019-873e-4d1b1871876c)

I have found that it needs to be "robot_length", using "robot_height" for the property doesn't work. 

//xxx example of how it has to be defined using Shuffleboard API with properties to make it work correctly. 

`frc::Shuffleboard::GetTab("Teleoperated").Add("Field", m_field).WithProperties({{"robot_width", nt::Value::MakeDouble(kTrackWidth.value())}, {"robot_length", nt::Value::MakeDouble(kWheelBase.value())}}).WithSize(10, 5).WithPosition(2, 0); `

**Comment by Gold872** [comment]
Didn't notice this until now, good catch! I'll update the docs and also make the existing code compatible with this property name in case if other people experience issues with it
