### ISSUE TITLE
Elastic not loading layout json

### ISSUE THREAD

**Issue by vichik123** [Gold872/elastic-dashboard#31]
We're trying to create a dashboard for our drivers, and we saved the layout in a [json](https://github.com/Gold872/elastic-dashboard/files/14418581/driver-dashboard-layout.json).
When we load the layout in elastic it just stops. Whether the simulation is running or not it doesn't load.
Did we forget something?

**Comment by Gold872** [comment]
That's interesting, the JSON file looks valid. Could you get me the log of the program? It's in `%userprofile%/AppData/Roaming/com.gold872/elastic_dashboard/elastic-log.txt`

When there's an error loading a JSON it should send an alert notification but it looks like something might be going wrong with that.

When I have access to our shop I'll try loading this layout.

**Comment by Gold872** [comment]
I was able to open it with my version just fine. Are both of your computers running on the same app version?

**Comment by oh-yes-0-fps** [comment]
Over a month since issue creators reply, this should probably be closed.

**Comment by Gold872** [comment]
I was unable to reproduce this issue, feel free to reopen if it happens again or there is more info about what is causing it
