### ISSUE TITLE
Color Theme Limited Range

### ISSUE THREAD

**Issue by lukesanborn** [Gold872/elastic-dashboard#33]
**Describe the bug**
Selecting bright colors, i.e., orange, defaults to a relatively muted hue. 

**To Reproduce**
1. Go to Settings, and go to color theme wheel
2. Pick a bright color and exit settings
3. See that the bright color gets changes to something else.

**Comment by DanPeled** [comment]
I found the reason for that bug, it is due to how the theme variant is set up, I am currently adding a PR that allows you to modify that
