### ISSUE TITLE
Dragging the color picker is slow

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#5]
https://youtu.be/O9o-1RtOvWg

**Comment by Gold872** [comment]
The video does not lead to a screen recording of the app, it's a MIDI video of Still Alive from Portal. Please send the correct video of this happening and I'll look into this issue

**Comment by daltzctr** [comment]
Whoops lol. 

https://github.com/Gold872/elastic-dashboard/assets/105223895/975e085b-87bc-430c-b40a-2fc0bea36ecc

**Comment by Gold872** [comment]
The color picker was rebuilding the entire widget tree every time the color was changed. I'm changing it so that it only updates when you click "Save"
