### ISSUE TITLE
Team number does not work if the roboRIO is not a `.2` address

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#6]
Should use mDNS instead.

![image](https://github.com/Gold872/elastic-dashboard/assets/105223895/6a935fbc-8370-4ad3-8d1a-2a1d4076f509)

**Comment by Gold872** [comment]
When would your roboRIO not end with `.2`? Generally the Driver Station interop should take care of finding the roboRIO's IP address regardless of what it is

**Comment by daltzctr** [comment]
If you're rio is static IPed to a different address, or you're not using an FRC radio ;)

**Comment by daltzctr** [comment]
Another thing is there's a bug in 2023 rio image that prevented some rios from being set to `.2`

**Comment by Gold872** [comment]
> If you're rio is static IPed to a different address, or you're not using an FRC radio ;)

This is meant to be used on robots with the required FRC radios and components, so I will likely not be adding in support for radios that aren't designed for FRC.

> Another thing is there's a bug in 2023 rio image that prevented some rios from being set to `.2`

I haven't heard or experienced such a bug, could you provide more info about it?

**Comment by daltzctr** [comment]
Every other dashboard (Glass, Smartdashboard, Shuffleboard) utilize MDNS resolution for team number, seems kinda weird to deviate from that behavior. It might also open things up to unexpected behavior at events. 

(I'm part of the core CS team at WPILib (my normal account is @daltz333)), but the roboRIO 1 image had an issue where it would be set to `DHCP` instead of `DHCP + Link Local`. The link local portion is what denotes it to fallback to a `.2` address.
