### ISSUE TITLE
Dragging the widget panel off of the screen makes it unrecoverable

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#7]

**Comment by Gold872** [comment]
Could you describe how you are able to drag widgets off the screen? It shouldn't let you place a widget in a location that it out of bounds

**Comment by daltzctr** [comment]
https://github.com/Gold872/elastic-dashboard/assets/105223895/34b36a38-d41a-4933-ba6e-a93d0efea913

**Comment by daltzctr** [comment]
This is a common scenario when unplugging external monitors of different resolutions
