### ISSUE TITLE
Entries sometimes don't have a fixed max width

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#8]
![image](https://github.com/Gold872/elastic-dashboard/assets/105223895/4a666b35-5229-4b21-bd63-64fc704bcfa1)

**Comment by daltzctr** [comment]
Maybe have a character maximum as well?

**Comment by Gold872** [comment]
I'll add both of these fixes in the next update. I'm not sure when you would want to make a tab with an extremely long name though
